name: Hostfully Exercise

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests
        run: npm test

      - name: Zip Cypress videos
        if: always()
        run: zip -r cypress_videos.zip cypress/videos/

      - name: Upload test videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress_videos
          path: cypress_videos.zip
          retention-days: 15

      - name: Lighthouse
        if: always()
        run: |
          npm install -g lighthouse
          lighthouse https://computer-database.gatling.io/computers --chrome-flags="--headless --window-size=1920,1080"
          lighthouse https://computer-database.gatling.io/computers/new --chrome-flags="--headless --window-size=1920,1080"
          lighthouse https://computer-database.gatling.io/computers/301 --chrome-flags="--headless --window-size=1920,1080"

      - name: Zip Lighthouse reports
        if: always()
        run: zip -r lighthouse_reports.zip *.html

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse_reports
          path: lighthouse_reports.zip
          retention-days: 15
